format = """\
    ${username}\
    ${hostname}\
    ${custom.pwd}\
    ${git_branch}\
    ${git_state}\
    ${git_status}\
    ${python}\
    ${rust}\
    ${cmd_duration}\
    ${line_break}\
    ${jobs}\
    ${shell}\
    ${character}\
    """

command_timeout = 50

# Active modules

[character]
error_symbol = "[✖](bold red)"
success_symbol = "[❯](bold green)"

[cmd_duration]
show_milliseconds = true
style = "yellow"

[custom.pwd]
command = "pwd"
description = "Prints the current working directory by compacting it."
style = "cyan"
format = "[$output]($style) "
when = "true"

[git_branch]
style = "purple"
symbol = ""

[package]
style = "208"
symbol = "p "

[python]
python_binary = "python3"
style = "yellow"
symbol = "Py "

[rust]
style = "red"
symbol = "Rs "

[git_state]
disabled = false

# The following takes too long to run on big repo
[git_status]
disabled = false
style = "yellow"
stashed = ""

[shell]
bash_indicator = "bash"
zsh_indicator = "zsh"
disabled = false

# Disabled modules
[aws]
disabled = true
[battery]
disabled = true
[conda]
disabled = true
[crystal]
disabled = true
[directory]
disabled = true
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[env_var]
disabled = true
[erlang]
disabled = true
# The following takes too long to run on big repo
[golang]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kubernetes]
disabled = true
[hg_branch]
disabled = true
[nim]
disabled = true
[nix_shell]
disabled = true
[nodejs]
disabled = true
[ocaml]
disabled = true
[php]
disabled = true
[purescript]
disabled = true
[ruby]
disabled = true
[singularity]
disabled = true
[terraform]
disabled = true
[time]
disabled = true
[zig]
disabled = true
