theme = "gruvbox"

[editor]
auto-info = true
completion-trigger-len = 1
idle-timeout = 0
line-number = "absolute"
mouse = false
rulers = [ 80, 100, 120 ]

[editor.file-picker]
hidden = false

[keys.normal.space]
g = "file_picker_in_current_directory"
