[[language]]
name = "rust"
auto-format = true

[language.config]
assist.importGranularity = "module"
# cargo.target = "x86_64-pc-windows-msvc"
# A little slower than a simple check, but so useful
checkOnSave.command = "clippy"
# Putting the target dir for RA inside target/ means it is automatically cleaned up
# by 'cargo clean' and hidden when there is a .gitignore or some global ignore for
# a Rust config
checkOnSave.extraArgs = ["--target-dir", "target/target-rust-analyzer"]
# checkOnSave.target = "x86_64-pc-windows-msvc"
# diagnostics.disabled = ["unresolved-proc-macro", "unresolved_proc_macro"]
hoverActions.references = true
lens.enumVariantReferences = true
lens.methodReferences = true
lens.references = true
# I have beefy machines, let's use them
lruCapacity = 256
procMacro.enable = true
workspace.symbol.search.kind = "all_symbols"



[[language]]
name = "toml"
indent = { tab-width = 4, unit = "    " }



[[language]]
name = "protobuf"
indent = { tab-width = 4, unit = "    " }



[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }