[[language]]
name = "rust"
auto-format = false

[language.config]
procMacro.enable = true
lruCapacity = 256
checkOnSave.command = "clippy"
checkOnSave.extraArgs = ["--target-dir", "target-rust-analyzer"]
# checkOnSave.target = "x86_64-pc-windows-msvc"
# cargo.target = "x86_64-pc-windows-msvc"
hoverActions.references = true
lens.methodReferences = true
lens.references = true
lens.enumVariantReferences = true
workspace.symbol.search.kind = "all_symbols"

# https://rust-analyzer.github.io/manual.html#user-snippet-completions
# [language.config.completion.snippets."test function"]
# prefix = ["tfn"]
# body = ["#[test]", "fn test_$1() {", "    $2", "}"]
# description = "Insert a new test function"
# scope = "item"

# [language.config.completion.snippets."test module"]
# prefix = ["tmod"]
# body = ["#[cfg(test)]", "mod tests {", "    use super::*", "",         "    #[test]", "    fn test_$1() {", "        $2", "    }", "}"]
# description = "Insert a new test module"
# scope = "item"



[[language]]
name = "toml"
indent = { tab-width = 4, unit = "    " }



[[language]]
name = "protobuf"
indent = { tab-width = 4, unit = "    " }



[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }